<?php

/**
 * @file
 * Install, update, etc. hooks.
 */

/**
 * Implements hook_install().
 */
function react_install() {
  drupal_set_message(t('React Library module has been enabled successfully.'), 'status');
}

/**
 * Implements hook_uninstall().
 */
function react_uninstall() {
  Drupal::configFactory()->getEditable('react.settings')->clear('react_addons')->save();
  drupal_set_message(t('Taxonomy manager module has been uninstalled successfully.'), 'status');
}
